apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: {{ .Values.frontendHpa.minReplicas }}
  maxReplicas: {{ .Values.frontendHpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.frontendHpa.targetCPUUtilizationPercentage}}
