version: '3.9' # this is a sneaky way to tell Docker to ignore version number
services:
  frontend:
    build: 
      context: ./ds_client #path of directory containing Dockerfile is relative to that of docker-compose file
    container_name: frontend
    networks:
      - my_network
    #depends_on:
    #  - backend
    #ports:
    #  - "8080:8080" 
    
  backend:
    build:
        context: ./ds_server 
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - my_network
    #volumes:

networks: 
  my_network:
#volumes:
