version: "3.9"

services:
  frontend:
    # image: sunnyeyles/ds_client:1.0
    build:
      context: ./ds_client_simple
    container_name: frontend
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - sapesu
    depends_on:
      - backend
    volumes:
      # mount the ds_client directory from the current directory into /usr/src/app inside the container
      - ./ds_client/:/usr/src/app
      # mount a named volume 'frontend_node_modules' to /usr/src/app/node_modules inside the container
      - frontend_node_modules:/usr/src/app/node_modules

  backend:
    image: sunnyeyles/ds_server:1.0
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - sapesu
    volumes:
      - ./ds_server:/app
    env_file:
      - ./ds_server/.env

  mongo:
    image: mongodb/mongodb-community-server:7.0.11-ubi8-20240621T081118Z
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ds_root
      MONGO_INITDB_ROOT_PASSWORD: ds_root_password
      MONGO_INITDB_DATABASE: messages
    networks:
      - sapesu

networks:
  sapesu:
    driver: bridge

volumes:
  frontend_node_modules:
