version: "3.9"

services:
  frontend:
    build:
      context: ./ds_client
    container_name: frontend
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - sapesu
    depends_on:
      - backend

  backend:
    build:
      context: ./ds_server
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - sapesu
    volumes:
      - ./ds_server:/app
    env_file:
      - ./ds_server/.env

  mongo:
    build:
      context: ./ds_database
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ds_root
      MONGO_INITDB_ROOT_PASSWORD: ds_root_password
      MONGO_INITDB_DATABASE: messages

    networks:
      - sapesu

networks:
  sapesu:
    driver: bridge
