version: "3.9"

services:
  frontend:
    build:
      context: ./ds_client
    container_name: frontend
    stdin_open: true
    ports:
      - "8080:8080"
    networks:
      - sapesu
    depends_on:
      - backend

  backend:
    build:
      context: ./ds_server
    container_name: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - sapesu
    volumes:
      - ./ds_server:/app

  mongo:
    build:
      context: ./mongo_db
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - sapesu
networks:
  sapesu:
    driver: bridge
