apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi
  minReplicas: {{ .Values.backendHpa.minReplicas }}
  maxReplicas: {{ .Values.backendHpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.backendHpa.targetCPUUtilizationPercentage}}
