apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ds-project-ingress
  namespace: ds-project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: letsencrypt-prod  # This will be detected by CertManager and it will use the issuer we defined.
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
