apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: ds-project
spec:
  accessModes:
  - {{ .Values.mongodbVolume.access }}
  resources:
    requests:
      storage: {{ .Values.mongodbVolume.storage }}