apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/ds-project-my-network: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: backend
          name: backend
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: backend-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: backend-cm0
          name: backend-cm0
