namespace: development

backendImage:
  repository: sunnyeyles/ds_server
  tag: "1.0"
  pullPolicy: Always
  restartPolicy: Always

backendService:
  name: backend
  port: 3001
  targetPort: 3001
  containerPort: 3001

backendHpa:
  minReplicas: 2
  maxReplicas: 6 
  targetCPUUtilizationPercentage: 70

# This is for the mongodb instance

mongodbVolume:
  name: mongodb-storage
  mountPath: /data/db
  accessMode: ReadWriteOnce
  storage: 10Gi

mongodbImage:
  repository: sunnyeyles/ds_database
  tag: "1.0"

mongodbEnv:
  MONGO_INITDB_ROOT_USERNAME: "ds_root"
  MONGO_INITDB_ROOT_PASSWORD: "ds_password"
  MONGO_INITDB_DATABASE: "messages"
  DATABASE_HOST: "127.0.0.1"
  DATABASE_PORT: "27017"
  DATABASE_COLLECTION: "messages"