apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          ports:
          - containerPort: {{ .Values.backendService.containerPort }}
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: {{ .Values.mongodbEnv.MONGO_INITDB_ROOT_USERNAME }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: {{ .Values.mongodbEnv.MONGO_INITDB_ROOT_PASSWORD }}
          - name : MONGO_INITDB_DATABASE
            value: {{ .Values.mongodbEnv.MONGO_INITDB_DATABASE }}
          - name: DATABASE_HOST
            value: "{{ toString .Values.mongodbEnv.DATABASE_HOST }}"
          - name: DATABASE_PORT
            value: "{{ toString .Values.mongodbEnv.DATABASE_PORT }}"
          - name: DATABASE_COLLECTION
            value: {{ .Values.mongodbEnv.DATABASE_COLLECTION }}
      restartPolicy: {{ .Values.backendImage.restartPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: {{ .Values.backendService.port }}
    targetPort: {{ .Values.backendService.targetPort }}
  type: ClusterIP
