apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Values.namespace }}

data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.MONGO_INITDB_ROOT_USERNAME | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.MONGO_INITDB_ROOT_PASSWORD | b64enc }}