namespace: production


backendImage:
  repository: sunnyeyles/ds_server
  tag: "1.0"
  pullPolicy: Always
  restartPolicy: Always

backendService:
  name: backend
  port: 3001
  targetPort: 3001
  containerPort: 3001

backendHpa:
  minReplicas: 2
  maxReplicas: 6 
  targetCPUUtilizationPercentage: 70

MONGO_INITDB_ROOT_USERNAME: atlas_username  # To be set in your environment via EXPORT atlas_username=
MONGO_INITDB_ROOT_PASSWORD: atlas_password  # Similarly
