name: Frontend CI
run-name: ${{ github.actor }} pushed a branch to frontend 🚀
on: [push]
jobs:
  Run tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

        run: |
          echo "🔍 Checking for .env files in the repository..."
          find ${{ github.workspace }} -name "*.env" -print
      
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
