# name: Backend development merge

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - development

# jobs:
#   build_and_push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Print working directory
#         run: pwd

#       - name: List files in current directory
#         run: ls -al

#       - name: List files in ds_server directory
#         run: ls -al ./ds_server

#       - name: Build Docker image
#         run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ds_server:1.0 -f ./ds_server/Dockerfile ./ds_server

#       - name: Push Docker image
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/ds_server:1.0
