name: Frontend

on:
  push:
    branches:
      - development

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: sunnyeyles/ds_client
        run: |
          docker build -t sunnyeyles/ds_client:1.0 -f ../../ds_client/Dockerfile ../../ds_client
          docker push $IMAGE_NAME:latest

      - name: Logout from Docker Hub
        run: docker logout
