name: Push Images

# pushes frontend and backend images to dockerhub when the development branch is pushed to
on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  frontend_build_and_push:
    name: frontend image push
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker build
        uses: docker/setup-buildx-action@v2

      - name: dockerhub login
        uses: docker/login-action@v2
        with:
          # inject sunnys dockerhub credentials from github secrets

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker image frontend
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ds_client:1.0 -f ./ds_client/Dockerfile ./ds_client

      - name: push frontend docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ds_client:1.0

  backend_build_and_push:
    name: backend image push
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker build
        uses: docker/setup-buildx-action@v2

      - name: dockerhub login
        uses: docker/login-action@v2
        # inject sunnys dockerhub credentials from github secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker image backend
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/ds_server:1.0 -f ./ds_server/Dockerfile ./ds_server

      - name: push backend docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ds_server:1.0
