name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform init
        run: terraform init

      - name: terraform apply
        # set environment variables from github secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CICD_USER_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CICD_USER_SECRET_KEY }}
          AWS_EC2_SSH_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
        run: |
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          terraform apply -auto-approve
