name: Terraform Workflow

on:
  pull_request:
    branches: [development]

  push:
    branches:
      - development

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check=true -diff=true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        uses: dflook/terraform-plan@v1

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: plan.out

  terraform-apply:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check=true -diff=true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
