name: "Terraform"

on:
  push:
  pull_request:
    branches: ["development"]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # this checks that the role specified has the right permissions
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::284445534808:role/sapesu
          aws-region: eu-west-3

      - name: checkout
        uses: actions/checkout@v3

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: init
        run: |
          cd terraform
          terraform init

      - name: format
        run: |
          cd terraform
          terraform fmt -check

      - name: plan
        run: |
          cd terraform
          terraform plan -input=false

      - name: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform
          terraform apply -auto-approve -input=false
