name: Deploy Infrastructure

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  tf_fmt:
    name: deploy
    runs-on: ubuntu-latest
    env:
      github-token: ${{ secrets.GH_TOKEN }}
      ssh-key: ${{secrets.AWS_EC2_SSH_KEY}}
      user-access-key: ${{secrets.CICD_USER_ACCESS_KEY}}
      user-secret-key: ${{secrets.CICD_USER_SECRET_KEY}}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init \
          -backend-config="access_key=${{ secrets.CICD_USER_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.CICD_USER_SECRET_KEY }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            terraform apply -auto-approve
