name: Test Build and Lint

# this will first run the linter, the linter will find any messy code or typescript errors
# after that is run it will build the application and make sure there are no errors in the build process
on:
  push:
  pull_request:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: |
          cd ds_client
          npm run lint
      - run: |
          cd ds_client
          npm run build --if-present
